const productConfig = {
  product1: {
    id: '1',
    title: 'SẢN PHẨM MỚI',
    urlDetail: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
    list: [
      {
        image: 'https://scontent.fsgn2-9.fna.fbcdn.net/v/t1.18169-9/17903834_1955584077997636_8078549794012623389_n.jpg?_nc_cat=106&ccb=1-7&_nc_sid=5f2048&_nc_eui2=AeFinkmWADWRczS6eADiUgAywfREzi8m8JzB9ETOLybwnEa5oVxWTMlwQWO1vTJRIt8xnPRjJmBeXfRFw2loPPic&_nc_ohc=8KojBzFNgJwAb7rD7yC&_nc_ht=scontent.fsgn2-9.fna&oh=00_AfDpxqh7pVpZtUHygrqVmTI7b6QJosM7mTicCaL0Wa6uqA&oe=6643741C',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '1200000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '900000',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '900000',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
    ],
  },
  product2: {
    id: '2',
    title: 'CAMERA  VÀ LINH KIỆN CAMERA CHÍNH HÃNG.',
    urlDetail: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
    list: [
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '900000',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '900000',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
    ],
  },
  product3: {
    id: '3',
    title: 'HOT TREND -HÀNG ĐIỆN  TỬ - ĐIỆN MÁY CHÍNH HÃNG.',
    urlDetail: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
    list: [
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '1000000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '900000',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '900000',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
    ],
  },
};

export default productConfig;
